version: '3'
services:
  app:
    tty: true
    build: .
    ports:
      - "${HTTP_PORT-8674}:8674"
      - "${TCP_PORT-2122}:2122"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    depends_on:
      - redis
      - mongo
    restart: on-failure
    entrypoint: node_modules/.bin/gulp
    environment:
      NODE_ENV: development

      MONGO_CORE_DSN: mongodb://mongo:27017/authenticus-core
      MONGO_TENANT_DSN: mongodb://mongo:27017/authenticus-tenant

      REDIS_CORE_DSN: redis://redis:6379/0
      REDIS_TENANT_DSN: redis://redis:6379/1

      HTTP_PORT: ${HTTP_PORT-8674}
      TCP_PORT: ${TCP_PORT-2122}
  redis:
    image: redis:alpine
  mongo:
    image: mongo:3.6
    volumes:
      - mongodb:/data/db
    ports:
      - "${DB_PORT-8675}:27017"
volumes:
  node_modules: {}
  mongodb: {}
